export const CHANGE_QUESTION_IS_SELECTED = 'CHANGE_QUESTION_IS_SELECTED';
export const GET_QUESTION_DATA = 'GET_QUESTION_DATA';
export const UPDATE_QUESTION_IS_CHECKED = 'UPDATE_QUESTION_IS_CHECKED';
export const UPDATE_LIST_ANSWER = 'UPDATE_LIST_ANSWER';
export const SET_USER_INFO = 'SET_USER_INFO';
